"""initial — full schema as of MVP3 + team_settings (MVP3.5)

Tables: teams, users, robots, contacts, conversations, messages, robot_tasks,
ai_prompts, ai_reply_logs, knowledge_bases, knowledge_documents,
knowledge_chunks, user_profiles, user_memories, team_settings.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-14
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'key', name='uq_ai_prompt_team_key')
    )
    with op.batch_alter_table('ai_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_prompts_team_id'), ['team_id'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_kb_team_name')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_team_id'), ['team_id'], unique=False)

    op.create_table('robots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('robot_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_page', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robots_robot_id'), ['robot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_robots_team_id'), ['team_id'], unique=False)

    op.create_table('team_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'key', name='uq_team_setting')
    )
    with op.batch_alter_table('team_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_settings_team_id'), ['team_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'external_id', name='uq_contact_robot_ext')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_team_id'), ['team_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_kb_id'), ['kb_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'contact_id', name='uq_conv_robot_contact')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_team_id'), ['team_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_doc_ord', ['doc_id', 'ord'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_kb_id'), ['kb_id'], unique=False)

    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_memories_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_memories_team_id'), ['team_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('preferences_json', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('last_summary_message_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_team_id'), ['team_id'], unique=False)

    op.create_table('robot_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robot_tasks_robot_id'), ['robot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_robot_tasks_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('external_msg_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['robot_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_msg_id', name='uq_msg_external')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_msg_conv_created', ['conversation_id', 'created_at'], unique=False)

    op.create_table('ai_reply_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_reply_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_reply_logs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_reply_logs_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_reply_logs_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_reply_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_reply_logs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_reply_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_ai_reply_logs_conversation_id'))

    op.drop_table('ai_reply_logs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_conv_created')

    op.drop_table('messages')
    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robot_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_robot_tasks_robot_id'))

    op.drop_table('robot_tasks')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_team_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_memories_team_id'))
        batch_op.drop_index(batch_op.f('ix_user_memories_contact_id'))

    op.drop_table('user_memories')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_kb_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_doc_id'))
        batch_op.drop_index('ix_chunk_doc_ord')

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_team_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_robot_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_contact_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_kb_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_team_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_robot_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('team_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_settings_team_id'))

    op.drop_table('team_settings')
    with op.batch_alter_table('robots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robots_team_id'))
        batch_op.drop_index(batch_op.f('ix_robots_robot_id'))

    op.drop_table('robots')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_team_id'))

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('ai_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_prompts_team_id'))

    op.drop_table('ai_prompts')
    op.drop_table('teams')
    # ### end Alembic commands ###
